heranca/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('accounts/profile/', views.profile, name='profile'),
    path('profile/', views.profile_logged, name='profile_logged'),
    path('dict/', views.dict_indigenous, name='dict_indigenous'),
    path('dict/<str:char>', views.dict_details, name='dict_details'),
    path('about/', views.about, name='about'),
    path('tribes/satere', views.tribe_satere, name='tribe_satere'),
    path('after_login/', views.after_login, name="after_login"),
    path('community/', views.community, name="community"),
    path('like_post/<int:post_id>/', views.like_post, name='like_post'),


]

quizes/urls.py
from django.urls import path
from .views import (
    quiz_list,
    quiz_view,
    )

app_name = "quizes"

urlpatterns = [
    path('', quiz_list, name='main-view'),
    path('<pk>/', quiz_view, name="quiz-view"),
]

website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from website.language import set_language 

urlpatterns = [
    path("admin/", admin.site.urls, name='admin'),
    path("", include('heranca.urls')),
    path('accounts/', include('allauth.urls')),
    path('quiz/', include('quizes.urls'), name='quizes')
]

urlpatterns = [
    *i18n_patterns(*urlpatterns, prefix_default_language=False),
    path("set_language/<str:language>", set_language, name="set-language"),
    ]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

heranca/models.py
from django.db import models
from PIL import Image
from io import BytesIO
from django.core.files.uploadedfile import InMemoryUploadedFile
from django.core.exceptions import ValidationError
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _

def validate_image_ratio(image):
    img = Image.open(image)
    width, height = img.size
    if width / height != 16 / 9:
        raise ValidationError("A proporção da imagem deve ser 16:9.")


class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='Posts/cover/%Y/%m/%d/', blank=True, null=True)
    description = models.CharField(max_length=255)
    is_public = models.BooleanField(default=True)
    likes_count = models.PositiveIntegerField(default=0)
    likes = models.ManyToManyField(User, related_name='liked_posts', blank=True)
    is_liked = models.BooleanField(default=False)

    def __str__(self):
        return self.description


    def like(self, user):
        if user not in self.likes.all():
            self.likes.add(user)
            self.is_liked = True
            self.likes_count += 1
            
        else:
            self.likes.remove(user)
            self.is_liked = False
            self.likes_count -= 1
        self.save()


class New(models.Model):
    image = models.ImageField(upload_to='News/cover/%Y/%m/%d/', blank=True, null=True)
    title = models.CharField(_("Titulo"), max_length=200)
    title_en = models.CharField(_("Title - (Titulo Ingles)"), max_length=220)
    link = models.URLField()
    is_public = models.BooleanField(default=True)

    def __str__(self):
        return self.title


class Dict_letter(models.Model):
    letter = models.AutoField(primary_key=True)
    letter_char = models.CharField(_("Letter Char"), max_length=1)
    alphabetical_order = models.IntegerField(_("Alphabetical Order"), default=0, blank=True)
    
    def get_words(self):
        return self.dict_indigenou_set.all()
    
    def __str__(self):
        return self.letter_char
    class Meta:
        ordering = ['letter_char']

class Dict_indigenou(models.Model):
    name = models.CharField(_("Name"), max_length=40)
    description = models.CharField(_("Description"), max_length=740)
    letter = models.ForeignKey(Dict_letter, on_delete=models.CASCADE)
    alphabetical_order = models.IntegerField(_("Alphabetical Order"), default=0, blank=True)
   

    def __str__(self):
        return self.name
    
    class Meta:
        ordering = ['name']


  

heranca/forms.py
from django import forms
from .models import Post

class LikeForm(forms.Form):
    action = forms.ChoiceField(choices=[('add', 'Adicionar Like'), ('remove', 'Remover Like')])


class NewPost(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['image', 'description']

heranca/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_protect
from .models import Post, New, Dict_indigenou, Dict_letter
from django.urls import reverse_lazy, reverse
from django.db.models import Q
from django.http import JsonResponse
from .forms import NewPost
from django.utils.translation import gettext_lazy as _


def index(request):
    user = request.user 
    news = New.objects.filter(is_public=True)
    if user.is_authenticated:
        page_title = user.username.title()
        return render(request, 'heranca/pages/index.html', {'page_title': page_title, 'news': news, 'user': user,})
    else:
        page_title = _("Inicio!")
        return render(request, 'heranca/pages/herança.html', {'page_title': page_title, 'news': news, 'user': user,})


@login_required(login_url=reverse_lazy('account_login'))
def profile(request,  click=''):
    user = request.user
    if click == '':
        return redirect("index")


def profile_logged(request):
    user = request.user
    return render(request, 'heranca/pages/profile.html',{
        'page_title': _("Perfil"),
        'user': user,
    })



@csrf_protect
def dict_indigenous(request):
    page_title = _("Dicionario")
    search_placeholder_text = "Busque pela letra!"
    letters = Dict_letter.objects.order_by('alphabetical_order')
    
    if request.method == "GET":
        page_title = "GET"
    elif request.method == 'POST':
        search_text = str(request.POST.get('header-search', '')).title()
        print(f'Search: {search_text}')
        search_result = letters.filter(
            Q(letter_char__icontains=search_text))
        letters = search_result
    
    return render(request, 'heranca/pages/dict.html', {
        'page_title': page_title,
        'letter_detail': False,
        'letters': letters,
        'search_placeholder_text': search_placeholder_text,
        'text_value': '',
    })
    

def dict_details(request, char):
    letter = get_object_or_404(
        Dict_letter,
        letter_char=char,
    )
    more_dict = Dict_letter.objects.exclude(letter_char=char).order_by("?")[:3]    
    
    page_title = _("Dicionario") + f" - {letter.letter_char}"
    
    return render(request, 'heranca/pages/dict.html', {
        'page_title': page_title,
        'letter_detail': True,
        'letter': letter,
        'more_dict': more_dict,
    })

def about(request):
    return render(request, 'heranca/pages/about.html',{
        'page_title': _("Quem somos"),
    })
    
def tribe_satere(request):
    return render(request, 'heranca/pages/tribe_satere.html',{
        'page_title': _("Sateré Mawé"),
    })


def after_login(request):
    return render(request, 'heranca/pages/after_login.html',{
        'page_title': _("Início"),
        
    })
    
    
@login_required(login_url=reverse_lazy('account_login')) 
def community(request):
    
    if request.method == 'POST':
        form = NewPost(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.is_public = True 
            post.save()
            return redirect('community')
    else:
        form = NewPost()
            
    
    
    user = request.user
    posts = Post.objects.filter(is_public=True)

    liked_posts = {}
    for post in posts:
        liked_posts[post.id] = user.is_authenticated and post.likes.filter(id=user.id).exists()


    return render(request, 'heranca/pages/community.html', {
        'page_title': _("Community"),
        'posts': posts,
        'liked_posts': liked_posts,
        'form': form,
    })
    



@login_required(login_url=reverse_lazy('account_login'))
def like_post(request, post_id):
    if request.method == 'POST':
        post = get_object_or_404(Post, id=post_id)
        post.like(request.user)
    return redirect('community') 

templates/heranca/pages/about.html
{% extends 'base_heranca.html' %}
{% load static %}
{% block title %}
    {{page_title}}
{% endblock title %}
{% block content %}
{% if '/en/' in request.path %}
<main class="main-width">
    <div class="top-title">
        <h1>About Us</h1>
    </div>
    <div class="about-info">
        <section class="about-info-text">
            <p>Welcome to <b>HERANÇA.BR</b> - Unveiling the History of the Indigenous Peoples of Manacapuru!</p>
        </section>
        <section class="about-info-text">
            <p>We are a platform dedicated to exploring and sharing the rich histories, origins, and heritages of the major indigenous peoples living around Manacapuru, offering a unique opportunity to understand their struggles, triumphs, and contributions to culture and society.</p>
        </section>
        <section class="about-info-text">
            <h1><b>Our Mission</b></h1>
            <p>Our mission is to create a deep and lasting awareness of the lives and experiences of the indigenous peoples who have shaped the landscapes and stories of Manacapuru and surrounding regions for centuries. Through authentic narratives and firsthand accounts, we seek to offer an intimate view of the hardships these peoples have faced or faced over time.</p>
        </section>
        <section class="about-info-text">
            <h1><b>Exploring Cultural Diversity</b></h1>
            <p>At HERANÇA.BR, we believe that understanding begins with learning. We invite you to dive into the fascinating traditions, languages, rituals, and beliefs of the indigenous peoples, discovering the depth of their ancestral wisdom. Each community is a unique link in the vast tapestry of indigenous culture, and we are committed to celebrating this diversity and preserving their narratives for future generations.</p>
        </section>
        <section class="about-info-text">
            <h1><b>Join the Indigenous Awareness Movement</b></h1>
            <p>By exploring this enriching space, you will be joining a vital movement of indigenous awareness. Learning about the difficulties faced by these communities is just the beginning. We aim to inspire action, promote empathy, and support initiatives that contribute to the well-being of these peoples. Be part of the positive change by informing yourself and sharing knowledge.</p>
        </section>
        <section class="about-info-text">
            <h1><b>Navigate Through Stories</b></h1>
            <p>Embark on a journey of discovery as we navigate through the stories of the indigenous peoples of Manacapuru. From ancient times to modern challenges, each page of HERANÇA.BR is a doorway to the past and a window to the future. Join us to explore the trails of memory and honor the heritages that connect us.</p>
        </section>
        <section class="about-info-text">
            <h1><b>Contribute to Preservation</b></h1>
            <p>Our commitment to cultural preservation does not end here. We invite everyone to share their own stories, photos, knowledge, and experiences related to the indigenous peoples of Manacapuru. By doing so, you help build a living and constantly evolving platform, dedicated to the preservation of indigenous narratives.</p>
        </section>
        <section class="about-info-text">
            <h1><b>Join us on this journey of learning, empathy, and respect for the rich heritage of the indigenous peoples of Manacapuru. Together, we can make a difference!</b></h1>
        </section>
        <section class="team">
            <div class="top-title">
                <h1>Our Team</h1>
            </div>
            <div class="team-mates">
                <div class="team-mate">
                    <div class="team-mate-img">
                        <img src="{% static 'heranca/images/about/camila.svg' %}" alt="">
                    </div>
                    <div class="team-mate-text">
                        <h1>Camila Brito</h1>
                        <h2>Designer and CEO.</h2>
                    </div>
                </div>
                <div class="team-mate">
                    <div class="team-mate-img">
                        <img src="{% static 'heranca/images/about/debora.svg' %}" alt="">
                    </div>
                    <div class="team-mate-text">
                        <h1>DEBORA CALHEIROS</h1>
                        <h2>Designer</h2>
                    </div>
                </div>
                <div class="team-mate">
                    <div class="team-mate-img">
                        <img src="{% static 'heranca/images/about/daiane.svg' %}" alt="">
                    </div>
                    <div class="team-mate-text">
                        <h1>DAIANE SOARES</h1>
                        <h2>Researcher</h2>
                    </div>
                </div>
                <div class="team-mate">
                    <div class="team-mate-img">
                        <img src="{% static 'heranca/images/about/henry.svg' %}" alt="">
                    </div>
                    <div class="team-mate-text">
                        <h1>HENRY COSTA</h1>
                        <h2>Researcher and Translator</h2>
                    </div>
                </div>
                <div class="team-mate">
                    <div class="team-mate-img">
                        <img src="{% static 'heranca/images/about/ana.svg' %}" alt="">
                    </div>
                    <div class="team-mate-text">
                        <h1>ANA VITÓRIA</h1>
                        <h2>Researcher</h2>
                    </div>
                </div>
            </div>
        </section>
        <section class="collaborators">
            <div class="top-title">
                <h1>Collaborators</h1>
            </div>
            <h2><b>Matheus Ricardo</b> - Programmer</h2>
            <h2><b>Tiago da Silva</b> - Programmer</h2>
            <h2><b>Patrícia</b> - Former Member and Researcher</h2>
        </section>
    </div>
    
</main>
{% else %}

<main class="main-width">
    <div class="top-title">
        <h1>Quem somos</h1>
    </div>
    <div class="about-info">
        <section class="about-info-text">
            <p>Bem-vindo ao <b>HERANÇA.BR</b> - Desvendando a História dos Povos Indígenas de Manacapuru!</p>
        </section>
        <section class="about-info-text">
            <p>Somos uma plataforma dedicada a explorar e compartilhar as ricas histórias, origens e heranças dos maiores povos indígenas que habitam as proximidades de Manacapuru, proporcionando uma oportunidade única de compreender suas lutas, triunfos e contribuições para a cultura e a sociedade.</p>
        </section>
        <section class="about-info-text">
            <h6><b>Nossa Missão</b></h6>
            <p>Nossa missão é criar uma conscientização profunda e duradoura sobre as vidas e experiências dos povos indígenas que há séculos moldam as paisagens e as histórias de Manacapuru e regiões circunvizinhas. Através de narrativas autênticas e relatos diretos, buscamos oferecer uma visão íntima das dificuldades que esses povos enfrentam ou enfrentaram ao longo do tempo.</p>
        </section>
        <section class="about-info-text">
            <h6><b>Explorando a Diversidade Cultural</b></h6>
            <p> No HERANÇA.BR, acreditamos que a compreensão começa com a aprendizagem. Convidamos você a mergulhar nas fascinantes tradições, línguas, rituais e crenças dos povos indígenas, descobrindo a profundidade de sua sabedoria ancestral. Cada comunidade é um elo único na vasta tapeçaria da cultura indígena, e estamos empenhados em celebrar essa diversidade e preservar suas narrativas para as gerações futuras.
            </p>
        </section>
        <section class="about-info-text">
            <h6><b>Junte-se à Conscientização Indígena</b></h6>
            <p>Ao explorar este espaço enriquecedor, você estará se unindo a um movimento vital de conscientização indígena. Aprender sobre as dificuldades enfrentadas por essas comunidades é apenas o começo. Queremos inspirar ações, promover a empatia e apoiar iniciativas que contribuam para o bem-estar desses povos. Seja parte da mudança positiva ao se informar e compartilhar conhecimento.
            </p>
        </section>
        <section class="about-info-text">
            <h6><b>Navegue pelas Histórias</b></h6>
            <p>Embarque em uma jornada de descoberta enquanto navegamos pelas histórias dos povos indígenas de Manacapuru. Desde os tempos ancestrais até os desafios modernos, cada página do HERANÇA.BR é uma porta para o passado e uma janela para o futuro. Junte-se a nós para explorar as trilhas da memória e honrar as heranças que nos conectam.</p>
        </section>
        <section class="about-info-text">
            <h6><b>Contribua para a Preservação</b></h6>
            <p>Nosso compromisso com a preservação cultural não termina aqui. Convidamos todos a compartilhar suas próprias histórias, fotos, conhecimentos e experiências relacionadas aos povos indígenas de Manacapuru. Ao fazer isso, você ajuda a construir uma plataforma viva e em constante evolução, dedicada à preservação das narrativas indígenas.</p>
        </section>
        <section class="about-info-text">
            <h6><b>Junte-se a nós nesta jornada de aprendizado, empatia e respeito pela rica herança dos povos indígenas de Manacapuru. Juntos, podemos fazer a diferença!</b></h6>
        </section>
        <section class="team">
            <div class="top-title">
                <h1>Nossa Equipe</h1>
            </div>
            <div class="team-mates">
                <div class="team-mate">
                    <div class="team-mate-img">
                        <img src="{% static 'heranca/images/about/camila.svg' %}" alt="">
                    </div>
                    <div class="team-mate-text">
                        <h1>Camila Brito</h1>
                        <h2>Designer e CEO.</h2>
                    </div>
                </div>
                <div class="team-mate">
                    <div class="team-mate-img">
                        <img src="{% static 'heranca/images/about/debora.svg' %}" alt="">
                    </div>
                    <div class="team-mate-text">
                        <h1>DEBORA CALHEIROS</h1>
                        <h2>Designer</h2>
                    </div>
                </div>
                <div class="team-mate">
                    <div class="team-mate-img">
                        <img src="{% static 'heranca/images/about/daiane.svg' %}" alt="">
                    </div>
                    <div class="team-mate-text">
                        <h1>DAIANE SOARES</h1>
                        <h2>Pesquisadora</h2>
                    </div>
                </div>
                <div class="team-mate">
                    <div class="team-mate-img">
                        <img src="{% static 'heranca/images/about/henry.svg' %}" alt="">
                    </div>
                    <div class="team-mate-text">
                        <h1>HENRY COSTA</h1>
                        <h2>Pesquisador e Tradutor</h2>
                    </div>
                </div>
                <div class="team-mate">
                    <div class="team-mate-img">
                        <img src="{% static 'heranca/images/about/ana.svg' %}" alt="">
                    </div>
                    <div class="team-mate-text">
                        <h1>ANA VITÓRIA</h1>
                        <h2>Pesquisadora</h2>
                    </div>
                </div>
            </div>
        </section>
        <section class="collaborators">
            <div class="top-title">
                <h1>Colaboradores</h1>
            </div>
            <h2><b>Matheus Ricardo</b> - Progamador</h2>
            <h2><b>Tiago da Silva</b> - Progamador</h2>
            <h2><b>Patrícia</b> - Ex-integrante e Pesquisadora</h2>
        </section>
    </div>
    
</main>
{% endif %}
<section class="img-gratient">
    <div class="bottom-img">
        <img src="{% static 'heranca/images/dict/bottom2.svg' %}" alt="">
    </div>
</section>
{% endblock content %}

templates/heranca/pages/after_login.html
{% extends "base_heranca.html" %}
{% load static %}
{% load i18n %}

{% block extra_styles %}
{% endblock extra_styles %}
{% block title %}{{page_title}}{% endblock title %}
{% block content %}
<main>
    <section>
        <div class="slide-button">
            <div class="slide-button-content">
                <button class="slide-prev-btn"><i class="fas fa-chevron-left"></i></button>
                <div class="slide-btn-center"></div>
                <button class="slide-next-btn"><i class="fas fa-chevron-right"></i></button>
            </div>
            <div class="slides owl-carousel">      
                <div class="slide">
                    <div class="slide-content">
                        <img class="slide-img" src="{% static '../media/News/cover/2023/08/16/ind1.png' %}" alt="">
                        <h1 class="login-title"><b>Explore o universno dos povos indígenas!!</b></h1>
                        <h2 class="login-text"><b>Mergulhe neste quiz repleto de curiosidades e saberes ancestrais!</b></h2>
                        <h4 class="login-see-more"><b>Jogue</b></h4>
                    </div>
                </div>
            </div>   
        </div>
    </section>
    <script>
        jQuery(document).ready(function($) {
            var owl = $('.owl-carousel');
            var prevBtn = $('.slide-prev-btn');
            var nextBtn = $('.slide-next-btn');
            var currentSlide = 0;
            
            owl.owlCarousel({
                center: true,
                loop: true,
                autoplay: true,
                autoplayTimeout: 10000, 
                items: 3,
                margin: 10,
                responsive: {
                    0: {
                        items: 1
                    },
                    768: {
                        items: 1
                    }
                }
            });


            owl.on('changed.owl.carousel', function(event) {
                currentSlide = event.item.index + 1;
            });
        
            prevBtn.on('click', function() {
                currentSlide = (currentSlide - 1) % owl.find('.owl-item').length + 1;
                updateSlideOption(currentSlide);
                owl.trigger('prev.owl.carousel');
            });
        
            nextBtn.on('click', function() {
                currentSlide = currentSlide % owl.find('.owl-item').length + 1;
                updateSlideOption(currentSlide);
                owl.trigger('next.owl.carousel');
            });
        
            $('.slide-option').on('change', function() {
                var position = $(this).data('position');
                currentSlide = position;
                owl.trigger('to.owl.carousel', position - 1);
            });
        
            function updateSlideOption(slideNumber) {
                $('.slide-option').prop('checked', false);
                $('#slide' + slideNumber).prop('checked', true);
            }
        });
        </script>        
</main>
{% endblock content %}

templates/heranca/pages/tribe_satere.html
{% extends 'base_heranca.html' %}
{% load static %}
{% block title %}
    {{page_title}}
{% endblock title %}
{% block content %}
{% if '/en/' in request.path %}

{% else %}
<main class="main-width">
    <div class="top-title">
        <h1>Sateré - Mawé</h1>
    </div>
    <div class="about-info">
        <section class="about-info-text about-info-map padding-none">
            <p> Sateré-Mawé significa “lagarta de fogo” e “papagaio inteligente e curioso”, esse é o nome da tribo indígena que habita a região do médio rio Amazonas, em duas terras indígenas, um pequeno grupo localizado na Ti Coatá-Laranjal da etnia Munduruku, e outro na Ti Andirá-Marau, que fica situada na fronteira dos estados do Amazonas e do Pará. 
            Eles também são encontrados morando em várias cidades no estado do Amazonas como Barreirinha, Maués, Nova Olinda do Norte, Parintins e em Manaus, onde vários indígenas Mawés (são chamados assim regionalmente) vivem em áreas periféricas e formam quatro aldeias urbanas nesta região.</p>
            <div class="tribe-location">
                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1019216.6025370689!2d-57.58062914491722!3d-3.7414180882445205!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x9260d4b4aad57c79%3A0x6a82dda1730d6f9!2sAndir%C3%A1-Marau!5e0!3m2!1spt-BR!2sbr!4v1700605650138!5m2!1spt-BR!2sbr" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
            </div>
        </section>
        <section class="about-info-text padding-none">
            <p> Ao longo dos séculos, os Sateré-Mawé enfrentaram uma série de desafios em relação à sua terra. Desde as missões jesuítas no século XVIII até a extração de borracha e a expansão econômica recente, seu território foi constantemente modificado. Essas mudanças resultaram na criação de fazendas, abertura de garimpos, desmatamento e na dominação da economia indígena pelos comerciantes ambulantes.</p>
            <p>Além disso, epidemias e perseguição forçaram os Sateré-Mawé a deixarem suas terras tradicionais, o que levou à redução de sua população. Nas décadas de 1980, eles lutaram contra a invasão da estatal francesa de petróleo Elf-Aquitaine, que causou impactos ambientais e a morte de indígenas por intoxicação. Felizmente, os Sateré-Mawé ganharam o processo judicial movido contra a empresa e também conseguiram impedir a construção de uma rodovia que atravessaria seu território.</p>
            <p>Atualmente, os jovens líderes indígenas estão lutando para ampliar o território de seu povo e combater a construção de dezenas de hidrelétricas na bacia do Amazonas, que ameaçam suas terras. Esses projetos representam um novo desafio para os Sateré-Mawé, que buscam preservar sua cultura e modo de vida.
            </p>
        </section>
        <section class="about-info-text ">
            <h1><b>Sateré-Mawé e o guaraná</b></h1>
        </section>
        <section class="about-info-text about-info-map padding-none">
            <div class="tribe-location">
                <img src="{% static 'heranca/images/tribes/satere2.svg' %}" alt="">
            </div>
            <p> Os Sateré-Mawé foram os primeiros a cultivar o guaraná, fruto originário da Amazônia, e que está diretamente traçado no plano ideológico do mito fundador desse povo. Os Mawés transformaram a planta Paullinia Cupana em uma espécie cultivada, introduzindo o cultivo e o processo de beneficiamento. O guaraná é originário das terras altas do rio Maués-Açu, que pertence ao território tradicional dos Sateré-Mawé.<br>O guaraná é o principal produto da economia dos Sateré-Mawé e é muito valorizado no mercado. A habilidade comercial dos Sateré-Mawé pode ser atribuída à importância cultural e econômica do guaraná para a comunidade.</p>
        </section>
        <section class="about-info-text">
            <p>   A primeira descrição do guaraná e sua importância para os Sateré-Mawé foi feita por volta de 1669, quando eles tiveram o primeiro contato com os colonizadores. Segundo o relato do padre João Felipe Betendorf, o guaraná é uma fruta encontrada na floresta dos Sateré-Mawé, que é seca e moída em forma de bolas. Quando essas bolas são dissolvidas em água e consumidas, fornecem energia e força aos indígenas, além de serem utilizadas no tratamento de doenças como febres, dores de cabeça e cãibras.<br>
            O guaraná nativo cultivado pelos Sateré-Mawé é extraído da natureza, sendo cuidadosamente coletado na floresta e submetido a um processo de secagem gradual em forno de barro. Além disso, é defumado de forma artesanal, a fim de preservar suas propriedades aromáticas e gustativas por um período prolongado. Apenas o excedente não utilizado pela comunidade é comercializado como grãos, pó ou em formato de bastão ou pão de guaraná.
            </p>
        </section>
        <section class="about-info-text ">
            <h1><b>Língua</b></h1>
        </section>
        <section class="about-info-text padding-none">
            <p>A língua Sateré-Mawé pertence à família linguística tupi, mas possui palavras que não são encontradas em outros dialetos tupis nem em outras famílias linguísticas.<br>
            Atualmente, os homens são bilíngues e falam tanto o Sateré-Mawé quanto o português. No entanto, em algumas aldeias mais isoladas, ainda existem mulheres que falam apenas o idioma nativo, mesmo após mais de trezentos anos de contato com os colonizadores brancos.</p>
        </section>

        <section class="about-info-text ">
            <h1><b>Cultura e artesanato</b></h1>
        </section>
        <section class="about-info-text about-info-map padding-none">
            <div class="tribe-location">
                <img src="{% static 'heranca/images/tribes/satere1.svg' %}" alt="">
            </div>
            <p> A sobrevivência das famílias Sateré-Mawé baseia-se na agricultura como principal fonte de sustento, com destaque para a produção de guaraná e mandioca. O excedente de alimentos como farinha, mel, castanhas, diversos tipos de frutos, resina, cipós e uma variedade de fibras vegetais é vendido nas cidades vizinhas.<br>
            Além disso, a comunidade indígena comercializa seus artesanatos e outros objetos de grande importância cultural. Essas obras são conhecidas como tessumi e são produzidas pelos homens utilizando caules e folhas de plantas locais, como caranã, arumã, entre outras matérias-primas encontradas na Floresta Amazônica. </p>
        </section>
        <section class="about-info-text ">
            <p>  Os artesãos confeccionam peneiras, cestos, esteiras, abanos, bolsas, chapéus e também utilizam esses mesmos materiais tradicionalmente para a construção das paredes e dos telhados de suas casas.</p>
        </section>
    </div>
    <div class="tribe-quiz">
        <section class="about-info-text ">
            <h1><b>Sateré Mawé ainda não tem quiz</b></h1>
            <h1><b><a class="text-decoration-none b-color" href="{% url "quizes:main-view" %}">Clique aqui para acessar os outros quizes sobre outros povos.</a></b></h1>
        </section>
    </div>
</main>
{% endif %}
<section class="img-gratient">
    <div class="bottom-img">
        <img src="{% static 'heranca/images/dict/bottom2.svg' %}" alt="">
    </div>
</section>
{% endblock content %}